<a href="https://colab.research.google.com/github/olegchistoprudov0210-ctrl/learning-quantum/blob/main/06_deutsch_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

# 1. Define the correct Hadamard gate
s2 = 1/np.sqrt(2)
H = s2 * np.array([[1, 1],
                   [1, -1]])

# 2. Build the initial state |01>
psi_0 = np.array([0, 1, 0, 0])

# Balanced Oracle
CNOT = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

I = np.eye(2)
# 3. Create 4x4 Hadamard (The "Cafe" logic)
H2 = np.kron(H, H)
H_final = np.kron(H, I)

# 4. Apply the layer of Hadamards
psi_1 = H2 @ psi_0
psi_2 = CNOT @ psi_1
# Deutch Algorithn
final_state = H_final @ psi_2

print("State after first layer:")
print(psi_1)

print("State after Oracle:")
print(psi_2)
print("The Result of Deutsch Algorithm:")
print(np.round(final_state, 2))
# We estimate that the first qubit is equal to 1
# This is the sum of the squares of the 3rd and 4th numbers
prob_1 = np.round(final_state[2]**2 + final_state[3]**2, 2)
print(f"Is the function balanced? (1 = Yes, 0 = No): {prob_1}")

State after first layer:
[ 0.5 -0.5  0.5 -0.5]
State after Oracle:
[ 0.5 -0.5 -0.5  0.5]
The Result of Deutsch Algorithm:
[ 0.    0.    0.71 -0.71]
Is the function balanced? (1 = Yes, 0 = No): 1.0
